package com.myspace.solarvillage_approvalprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Applicant Name")
	private java.lang.String applicantName;
	@org.kie.api.definition.type.Label(value = "Applicant Address")
	private java.lang.String applicantAddress;
	@org.kie.api.definition.type.Label(value = "Annual Income")
	private java.lang.String applicantAnnualIncome;
	@org.kie.api.definition.type.Label(value = "HOA Meeting Date")
	private java.util.Date hoaMeetingDate;

	public Application() {
	}

	public java.lang.String getApplicantName() {
		return this.applicantName;
	}

	public void setApplicantName(java.lang.String applicantName) {
		this.applicantName = applicantName;
	}

	public java.lang.String getApplicantAddress() {
		return this.applicantAddress;
	}

	public void setApplicantAddress(java.lang.String applicantAddress) {
		this.applicantAddress = applicantAddress;
	}

	public java.lang.String getApplicantAnnualIncome() {
		return this.applicantAnnualIncome;
	}

	public void setApplicantAnnualIncome(java.lang.String applicantAnnualIncome) {
		this.applicantAnnualIncome = applicantAnnualIncome;
	}

	public java.util.Date getHoaMeetingDate() {
		return this.hoaMeetingDate;
	}

	public void setHoaMeetingDate(java.util.Date hoaMeetingDate) {
		this.hoaMeetingDate = hoaMeetingDate;
	}

	public Application(java.lang.String applicantName,
			java.lang.String applicantAddress,
			java.lang.String applicantAnnualIncome,
			java.util.Date hoaMeetingDate) {
		this.applicantName = applicantName;
		this.applicantAddress = applicantAddress;
		this.applicantAnnualIncome = applicantAnnualIncome;
		this.hoaMeetingDate = hoaMeetingDate;
	}

}