package com.myspace.solarvillage_approvalprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResidentialElectricalPermResp implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Electrical Permit ID")
	private String elecPermitId;
	@org.kie.api.definition.type.Label("Status of the permit")
	private java.lang.String status;

	public ResidentialElectricalPermResp() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getElecPermitId() {
		return this.elecPermitId;
	}

	public void setElecPermitId(java.lang.String elecPermitId) {
		this.elecPermitId = elecPermitId;
	}

	public ResidentialElectricalPermResp(java.lang.String elecPermitId,
			java.lang.String status) {
		this.elecPermitId = elecPermitId;
		this.status = status;
	}

}