package com.myspace.solarvillage_approvalprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResidentialStructuralPermReq implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ResidentialStructuralPermReq() {
    }




}