package com.myspace.solarvillage_approvalprocess;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SalesRep implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Application Details")
	private com.myspace.solarvillage_approvalprocess.Application application;
	@org.kie.api.definition.type.Label(value = "Sales Rep Accepted")
	private java.lang.Boolean salesRepAccepted;

	public SalesRep() {
	}

	public com.myspace.solarvillage_approvalprocess.Application getApplication() {
		return this.application;
	}

	public void setApplication(
			com.myspace.solarvillage_approvalprocess.Application application) {
		this.application = application;
	}

	public java.lang.Boolean getSalesRepAccepted() {
		return this.salesRepAccepted;
	}

	public void setSalesRepAccepted(java.lang.Boolean salesRepAccepted) {
		this.salesRepAccepted = salesRepAccepted;
	}

	public SalesRep(
			com.myspace.solarvillage_approvalprocess.Application application,
			java.lang.Boolean salesRepAccepted) {
		this.application = application;
		this.salesRepAccepted = salesRepAccepted;
	}

}